# ROS2 Launch Tester Configuration Example
# Specify what to expect from your launch file

# List of nodes that should be running
nodes:
  - "/turtle_teleop"
  - "/turtlesim"

# List of topics that should exist
topics:
  - "/turtle1/cmd_vel"
  - "/turtle1/color_sensor"
  - "/turtle1/pose"

# List of services that should be available
services:
  - "/turtle1/set_pen"
  - "/turtle1/teleport_absolute"
  - "/turtle1/teleport_relative"
  - "/reset"
  - "/spawn"

# Parameters to check (node_name/param_name: expected_value)
parameters:
  "/turtlesim/background_r": 69
  "/turtlesim/background_g": 86
  "/turtlesim/background_b": 255

# Optional timeout settings
timeout:
  startup: 5.0    # seconds to wait for launch file startup
  tests: 30.0     # seconds to wait for each test category

